// contract/tools/lib.mjs — 契约加载与四端渲染。gen.mjs 与 check.mjs 共用。
import { readFileSync } from 'node:fs'
import { join } from 'node:path'
import { createHash } from 'node:crypto'

export const DATA_FILES = ['transfer-state.json', 'strings.json', 'tokens.json', 'capabilities.json']
export const HEADER = 'GENERATED by contract/tools/gen.mjs from contract/*.json — 不要手改，改 contract/ 再跑 gen'

export function sha256(text) {
  return createHash('sha256').update(text).digest('hex')
}

function readJson(root, name) {
  return JSON.parse(readFileSync(join(root, 'contract', name), 'utf8'))
}

export function loadContract(root) {
  return {
    root,
    state: readJson(root, 'transfer-state.json'),
    strings: readJson(root, 'strings.json'),
    tokens: readJson(root, 'tokens.json'),
    caps: readJson(root, 'capabilities.json'),
    manifest: readJson(root, 'contract.json'),
  }
}

/** 重新计算 contract.json 应有的内容 */
export function manifestFor(root, version) {
  const files = {}
  for (const f of DATA_FILES) files[f] = sha256(readFileSync(join(root, 'contract', f), 'utf8'))
  return { version, files }
}

const H = (comment) => `${comment} ${HEADER}\n`
const q = (s) => JSON.stringify(s)

function parseColor(v) {
  const m = /^rgba\((\d+),\s*(\d+),\s*(\d+),\s*([\d.]+)\)$/.exec(v)
  if (m) return { r: +m[1], g: +m[2], b: +m[3], a: +m[4] }
  const hex = v.replace('#', '')
  return { r: parseInt(hex.slice(0, 2), 16), g: parseInt(hex.slice(2, 4), 16), b: parseInt(hex.slice(4, 6), 16), a: 1, hex }
}
const swiftColor = (v) => {
  const c = parseColor(v)
  if (c.hex) return `Color(hex: 0x${c.hex.toUpperCase()})`
  const f = (n) => (n / 255).toFixed(3)
  return `Color(.sRGB, red: ${f(c.r)}, green: ${f(c.g)}, blue: ${f(c.b)}, opacity: ${c.a.toFixed(2)})`
}
const kotlinColor = (v) => {
  const c = parseColor(v)
  const a = Math.round(c.a * 255)
  const hex = [a, c.r, c.g, c.b].map((n) => n.toString(16).padStart(2, '0')).join('').toUpperCase()
  return `0x${hex}L`
}

// ---- wxss ----
function renderWxss(c) {
  const t = c.tokens, n = t.wxssNames, f = t.unit.wxssSpacingFactor
  const lines = [`/* ${HEADER} */`, 'page {']
  for (const grp of ['L', 'D', 'S']) for (const [k, v] of Object.entries(t[grp])) lines.push(`  --${n[grp][k]}: ${v};`)
  for (const [k, v] of Object.entries(t.Sp)) lines.push(`  --${k === 'gutter' ? 'gutter' : k}: ${v * f}rpx;`)
  for (const [k, v] of Object.entries(t.Ty)) lines.push(`  --t-${k}: ${v}${t.unit.typeUnit};`)
  lines.push(`  --font-sans: ${t.font.sans};`, `  --font-mono: ${t.font.mono};`)
  lines.push(`  --d-fast: ${t.motion.fastMs}ms;`, `  --d-base: ${t.motion.baseMs}ms;`, `  --d-slow: ${t.motion.slowMs}ms;`)
  lines.push(`  --e-out: ${t.motion.easeOut};`, `  --e-in: ${t.motion.easeIn};`)
  lines.push(`  --touch-min: ${t.touchMin * f}rpx;`, '}', '')
  const footer = readFileSync(join(c.root, 'contract', 'tools', 'wxss-footer.css'), 'utf8')
  return lines.join('\n') + '\n' + footer
}

// ---- TS ----
function renderTsStates(c) {
  const s = c.state
  const union = (arr) => arr.map(q).join(' | ')
  return H('//') + `export const CONTRACT_VERSION = ${s.version}
export type QueueState = ${union(s.states)}
export const STATES: readonly QueueState[] = ${q(s.states)}
export const STATE_ALIASES: Record<string, QueueState> = ${q(s.aliases)}
export type Phase = ${union(Object.keys(s.phases))}
export const PHASE_OF: Record<QueueState, Phase> = ${q(Object.fromEntries(Object.entries(s.phases).flatMap(([p, v]) => v.states.map((st) => [st, p]))))}
export const PHASE_LABEL_KEY: Record<Phase, string> = ${q(Object.fromEntries(Object.entries(s.phases).map(([p, v]) => [p, v.label])))}
export const PHASE_DOT: Record<Phase, string> = ${q(Object.fromEntries(Object.entries(s.phases).map(([p, v]) => [p, v.dot])))}
export const FAILED_DOT = ${q(s.failedDot)}
export const STATE_TEXT_KEY: Record<QueueState, string> = ${q(s.stateText)}
export const STATE_DETAIL_KEY: Record<QueueState, string> = ${q(s.stateDetail)}
export const WHERE_KEY: Record<QueueState, string> = ${q(s.whereItIs)}
export const RETRY_DELAYS_MS: readonly number[] = ${q(s.retryDelaysMs)}
export const MAX_AUTO_RETRIES = ${s.maxAutoRetries}
export type TransferEvent = ${union(s.events)}
export const TRANSITIONS: ReadonlyArray<{ from: QueueState; event: TransferEvent; to: QueueState; guard?: string }> = ${JSON.stringify(s.transitions, null, 2)}
export const DELETE_WARN_ORDER: readonly Phase[] = ${q(s.deleteWarning.order)}
export const DELETE_WARN_LEVEL: Record<Phase, 'unsent' | 'staged' | 'landed'> = ${q(s.deleteWarning.levels)}
export const DELETE_WARN_KEY: Record<'unsent' | 'staged' | 'landed', string> = ${q(s.deleteWarning.keys)}
`
}
function renderTsStrings(c) {
  return H('//') + `export const STRINGS: Record<string, { 'zh-Hans': string; en: string }> = ${JSON.stringify(c.strings, null, 2)}\n`
}
function renderTsCaps(c, client) {
  const caps = Object.fromEntries(Object.entries(c.caps.capabilities).map(([k, v]) => [k, v[client]]))
  const notice = Object.fromEntries(Object.entries(c.caps.capabilities).filter(([, v]) => v.degradedNotice).map(([k, v]) => [k, v.degradedNotice]))
  return H('//') + `export const CLIENT = ${q(client)}
export const CAPS = ${JSON.stringify(caps, null, 2)} as const
export const DEGRADED_NOTICE: Record<string, string> = ${q(notice)}
`
}

// ---- Swift ----
function renderSwiftTokens(c) {
  const t = c.tokens
  const grp = (name, obj, fn) => `    enum ${name} {\n${Object.entries(obj).map(([k, v]) => `        static let ${k} = ${fn(v)}`).join('\n')}\n    }\n`
  const num = (name, obj) => `    enum ${name} {\n${Object.entries(obj).map(([k, v]) => `        static let ${k}: CGFloat = ${v}`).join('\n')}\n    }\n`
  return H('//') + `import SwiftUI

/// 设计令牌。F（字体）与 A（动效）在 Design/Typography.swift 里以 extension 补齐。
enum T {
${grp('L', t.L, swiftColor)}
${grp('D', t.D, swiftColor)}
${grp('S', t.S, swiftColor)}
${num('Sp', t.Sp)}
${num('Ty', t.Ty)}
    enum Motion {
        static let fast: Double = ${(t.motion.fastMs / 1000).toFixed(2)}
        static let base: Double = ${(t.motion.baseMs / 1000).toFixed(2)}
        static let slow: Double = ${(t.motion.slowMs / 1000).toFixed(2)}
    }
    static let touchMin: CGFloat = ${t.touchMin}
    static let contractVersion = ${t.version}
}
`
}
const swiftDict = (obj) => `[${Object.entries(obj).map(([k, v]) => `${q(k)}: ${q(v)}`).join(', ')}]`
function renderSwiftStrings(c) {
  const rows = Object.entries(c.strings).map(([k, v]) => `        ${q(k)}: [${q('zh-Hans')}: ${q(v['zh-Hans'])}, ${q('en')}: ${q(v.en)}],`).join('\n')
  return H('//') + `enum ContractStrings {\n    static let table: [String: [String: String]] = [\n${rows}\n    ]\n}\n`
}
function renderSwiftStates(c) {
  const s = c.state
  const tr = s.transitions.map((t) => `        (from: ${q(t.from)}, event: ${q(t.event)}, to: ${q(t.to)}, guard: ${t.guard ? q(t.guard) : 'nil'}),`).join('\n')
  return H('//') + `enum ContractStates {
    static let version = ${s.version}
    static let states: [String] = ${q(s.states)}
    static let aliases: [String: String] = ${swiftDict(s.aliases)}
    static let phaseOf: [String: String] = ${swiftDict(Object.fromEntries(Object.entries(s.phases).flatMap(([p, v]) => v.states.map((st) => [st, p]))))}
    static let phaseLabelKey: [String: String] = ${swiftDict(Object.fromEntries(Object.entries(s.phases).map(([p, v]) => [p, v.label])))}
    static let phaseDot: [String: String] = ${swiftDict(Object.fromEntries(Object.entries(s.phases).map(([p, v]) => [p, v.dot])))}
    static let failedDot = ${q(s.failedDot)}
    static let stateTextKey: [String: String] = ${swiftDict(s.stateText)}
    static let stateDetailKey: [String: String] = ${swiftDict(s.stateDetail)}
    static let whereKey: [String: String] = ${swiftDict(s.whereItIs)}
    static let retryDelaysMs: [Int] = ${q(s.retryDelaysMs)}
    static let maxAutoRetries = ${s.maxAutoRetries}
    static let events: [String] = ${q(s.events)}
    static let transitions: [(from: String, event: String, to: String, guard: String?)] = [
${tr}
    ]
    static let deleteWarnOrder: [String] = ${q(s.deleteWarning.order)}
    static let deleteWarnLevel: [String: String] = ${swiftDict(s.deleteWarning.levels)}
    static let deleteWarnKey: [String: String] = ${swiftDict(s.deleteWarning.keys)}
}
`
}
function renderSwiftCaps(c) {
  const v = (x) => x === null ? 'nil' : typeof x === 'string' ? q(x) : String(x)
  const caps = c.caps.capabilities
  return H('//') + `enum ContractCapabilities {
    static let client = "ios"
    static let backgroundUpload: Bool = ${caps.backgroundUpload.ios}
    static let maxVideoSeconds: Int? = ${v(caps.maxVideoSeconds.ios)}
    static let continuousSegments: Bool = ${caps.continuousSegments.ios}
    /// true / false，或 "runtime" 表示运行时探测
    static let glassBlur: String = ${q(String(caps.glassBlur.ios))}
    static let deviceAttestation: Bool = ${caps.deviceAttestation.ios}
    static let degradedNotice: [String: String] = ${swiftDict(Object.fromEntries(Object.entries(caps).filter(([, x]) => x.degradedNotice).map(([k, x]) => [k, x.degradedNotice])))}
}
`
}

// ---- Kotlin ----
/** Kotlin 字符串字面量里 $ 起模板引用，词典里真出现 $ 时必须转义 */
const kq = (s) => JSON.stringify(s).replace(/\$/g, '\\$')
const ktMap = (obj) => `mapOf(${Object.entries(obj).map(([k, v]) => `${kq(k)} to ${kq(v)}`).join(', ')})`
function renderKtTokens(c) {
  const t = c.tokens
  const grp = (name, obj, fn) => `    object ${name} {\n${Object.entries(obj).map(([k, v]) => `        const val ${k}: Long = ${fn(v)}`).join('\n')}\n    }`
  const num = (name, obj) => `    object ${name} {\n${Object.entries(obj).map(([k, v]) => `        const val ${k}: Int = ${v}`).join('\n')}\n    }`
  return H('//') + `package com.aiworkdeck.contract

/** 颜色为 ARGB Long；间距单位 dp，字号单位 sp。 */
object T {
${grp('L', t.L, kotlinColor)}
${grp('D', t.D, kotlinColor)}
${grp('S', t.S, kotlinColor)}
${num('Sp', t.Sp)}
${num('Ty', t.Ty)}
    object Motion { const val fastMs: Int = ${t.motion.fastMs}; const val baseMs: Int = ${t.motion.baseMs}; const val slowMs: Int = ${t.motion.slowMs} }
    const val touchMin: Int = ${t.touchMin}
    const val contractVersion: Int = ${t.version}
}
`
}
function renderKtStrings(c) {
  const rows = Object.entries(c.strings).map(([k, v]) => `        ${kq(k)} to mapOf("zh-Hans" to ${kq(v['zh-Hans'])}, "en" to ${kq(v.en)}),`).join('\n')
  return H('//') + `package com.aiworkdeck.contract\n\nobject ContractStrings {\n    val table: Map<String, Map<String, String>> = mapOf(\n${rows}\n    )\n}\n`
}
function renderKtStates(c) {
  const s = c.state
  const tr = s.transitions.map((t) => `        Transition(${kq(t.from)}, ${kq(t.event)}, ${kq(t.to)}, ${t.guard ? kq(t.guard) : 'null'}),`).join('\n')
  return H('//') + `package com.aiworkdeck.contract

data class Transition(val from: String, val event: String, val to: String, val guard: String?)

object ContractStates {
    const val version: Int = ${s.version}
    val states: List<String> = listOf(${s.states.map(kq).join(', ')})
    val aliases: Map<String, String> = ${ktMap(s.aliases)}
    val phaseOf: Map<String, String> = ${ktMap(Object.fromEntries(Object.entries(s.phases).flatMap(([p, v]) => v.states.map((st) => [st, p]))))}
    val phaseLabelKey: Map<String, String> = ${ktMap(Object.fromEntries(Object.entries(s.phases).map(([p, v]) => [p, v.label])))}
    val phaseDot: Map<String, String> = ${ktMap(Object.fromEntries(Object.entries(s.phases).map(([p, v]) => [p, v.dot])))}
    const val failedDot: String = ${kq(s.failedDot)}
    val stateTextKey: Map<String, String> = ${ktMap(s.stateText)}
    val stateDetailKey: Map<String, String> = ${ktMap(s.stateDetail)}
    val whereKey: Map<String, String> = ${ktMap(s.whereItIs)}
    val retryDelaysMs: List<Int> = listOf(${s.retryDelaysMs.join(', ')})
    const val maxAutoRetries: Int = ${s.maxAutoRetries}
    val events: List<String> = listOf(${s.events.map(kq).join(', ')})
    val transitions: List<Transition> = listOf(
${tr}
    )
    val deleteWarnOrder: List<String> = listOf(${s.deleteWarning.order.map(kq).join(', ')})
    val deleteWarnLevel: Map<String, String> = ${ktMap(s.deleteWarning.levels)}
    val deleteWarnKey: Map<String, String> = ${ktMap(s.deleteWarning.keys)}
}
`
}
function renderKtCaps(c) {
  const caps = c.caps.capabilities
  const v = (x) => x === null ? 'null' : typeof x === 'string' ? kq(x) : String(x)
  return H('//') + `package com.aiworkdeck.contract

object ContractCapabilities {
    const val client: String = "android"
    const val backgroundUpload: Boolean = ${caps.backgroundUpload.android}
    val maxVideoSeconds: Int? = ${v(caps.maxVideoSeconds.android)}
    const val continuousSegments: Boolean = ${caps.continuousSegments.android}
    /** "true" / "false" / "runtime" */
    const val glassBlur: String = ${kq(String(caps.glassBlur.android))}
    const val deviceAttestation: Boolean = ${caps.deviceAttestation.android}
    val degradedNotice: Map<String, String> = ${ktMap(Object.fromEntries(Object.entries(caps).filter(([, x]) => x.degradedNotice).map(([k, x]) => [k, x.degradedNotice])))}
}
`
}

// ---- ArkTS ----
function renderEtsTokens(c) {
  const t = c.tokens
  return H('//') + `/** 颜色为 CSS 字符串；间距单位 vp，字号单位 fp。 */
export const T = ${JSON.stringify({ L: t.L, D: t.D, S: t.S, Sp: t.Sp, Ty: t.Ty, Motion: { fastMs: t.motion.fastMs, baseMs: t.motion.baseMs, slowMs: t.motion.slowMs }, touchMin: t.touchMin, contractVersion: t.version }, null, 2)} as const
`
}
function renderEtsStrings(c) {
  return H('//') + `export const ContractStrings: Record<string, Record<string, string>> = ${JSON.stringify(c.strings, null, 2)}\n`
}
function renderEtsStates(c) {
  const s = c.state
  return H('//') + `export const ContractStates = ${JSON.stringify({
    version: s.version, states: s.states, aliases: s.aliases,
    phaseOf: Object.fromEntries(Object.entries(s.phases).flatMap(([p, v]) => v.states.map((st) => [st, p]))),
    phaseLabelKey: Object.fromEntries(Object.entries(s.phases).map(([p, v]) => [p, v.label])),
    phaseDot: Object.fromEntries(Object.entries(s.phases).map(([p, v]) => [p, v.dot])),
    failedDot: s.failedDot, stateTextKey: s.stateText, stateDetailKey: s.stateDetail, whereKey: s.whereItIs,
    retryDelaysMs: s.retryDelaysMs, maxAutoRetries: s.maxAutoRetries, events: s.events, transitions: s.transitions,
    deleteWarnOrder: s.deleteWarning.order, deleteWarnLevel: s.deleteWarning.levels, deleteWarnKey: s.deleteWarning.keys,
  }, null, 2)} as const
`
}
function renderEtsCaps(c) {
  const caps = c.caps.capabilities
  return H('//') + `export const ContractCapabilities = ${JSON.stringify({
    client: 'harmony',
    ...Object.fromEntries(Object.entries(caps).map(([k, v]) => [k, v.harmony])),
    degradedNotice: Object.fromEntries(Object.entries(caps).filter(([, x]) => x.degradedNotice).map(([k, x]) => [k, x.degradedNotice])),
  }, null, 2)} as const
`
}

/** 全部生成物：相对路径 → 内容 */
export function outputs(c) {
  const kt = 'android/contract/src/main/kotlin/com/aiworkdeck/contract'
  const ets = 'harmony/contract/src/main/ets'
  return new Map([
    ['miniprogram/styles/tokens.wxss', renderWxss(c)],
    ['miniprogram/utils/contract/states.ts', renderTsStates(c)],
    ['miniprogram/utils/contract/strings.ts', renderTsStrings(c)],
    ['miniprogram/utils/contract/capabilities.ts', renderTsCaps(c, 'miniprogram')],
    ['ios/Sources/Contract/Tokens.swift', renderSwiftTokens(c)],
    ['ios/Sources/Contract/Strings.swift', renderSwiftStrings(c)],
    ['ios/Sources/Contract/States.swift', renderSwiftStates(c)],
    ['ios/Sources/Contract/Capabilities.swift', renderSwiftCaps(c)],
    [`${kt}/Tokens.kt`, renderKtTokens(c)],
    [`${kt}/Strings.kt`, renderKtStrings(c)],
    [`${kt}/States.kt`, renderKtStates(c)],
    [`${kt}/Capabilities.kt`, renderKtCaps(c)],
    [`${ets}/Tokens.ets`, renderEtsTokens(c)],
    [`${ets}/Strings.ets`, renderEtsStrings(c)],
    [`${ets}/States.ets`, renderEtsStates(c)],
    [`${ets}/Capabilities.ets`, renderEtsCaps(c)],
  ])
}
