// contract/tools/lib.mjs — 契约加载与四端渲染。gen.mjs 与 check.mjs 共用。
import { readFileSync } from 'node:fs'
import { join } from 'node:path'
import { createHash } from 'node:crypto'

export const DATA_FILES = ['transfer-state.json', 'strings.json', 'tokens.json', 'capabilities.json']
export const HEADER = 'GENERATED by contract/tools/gen.mjs from contract/*.json — 不要手改，改 contract/ 再跑 gen'

export function sha256(text) {
  return createHash('sha256').update(text).digest('hex')
}

function readJson(root, name) {
  return JSON.parse(readFileSync(join(root, 'contract', name), 'utf8'))
}

export function loadContract(root) {
  return {
    root,
    state: readJson(root, 'transfer-state.json'),
    strings: readJson(root, 'strings.json'),
    tokens: readJson(root, 'tokens.json'),
    caps: readJson(root, 'capabilities.json'),
    manifest: readJson(root, 'contract.json'),
  }
}

/** 重新计算 contract.json 应有的内容 */
export function manifestFor(root, version) {
  const files = {}
  for (const f of DATA_FILES) files[f] = sha256(readFileSync(join(root, 'contract', f), 'utf8'))
  return { version, files }
}
