import { test } from 'node:test'
import assert from 'node:assert/strict'
import { readFileSync, mkdtempSync, cpSync, writeFileSync, existsSync, mkdirSync } from 'node:fs'
import { join } from 'node:path'
import { tmpdir } from 'node:os'
import { loadContract, sha256, DATA_FILES, outputs } from '../contract/tools/lib.mjs'
import { runChecks, referenceMoneyDisplay } from '../contract/tools/check.mjs'

const ROOT = join(import.meta.dirname, '..')

function tempCopy(): string {
  const dir = mkdtempSync(join(tmpdir(), 'awd-contract-'))
  cpSync(join(ROOT, 'contract'), join(dir, 'contract'), { recursive: true })
  return dir
}

test('contract.json 的 sha 与四个数据文件一致', () => {
  const c = loadContract(ROOT)
  for (const f of DATA_FILES) {
    const actual = sha256(readFileSync(join(ROOT, 'contract', f), 'utf8'))
    assert.equal(c.manifest.files[f], actual, `${f} 的 sha 过期，跑 node contract/tools/gen.mjs`)
  }
})

test('状态机引用闭合：真仓干净，打断一处引用就要红', () => {
  // 闭合检查已经搬进 check.mjs 的 checkReferences，这里只守它的行为
  assert.deepEqual(runChecks(ROOT, { quick: true }).problems, [])

  const dir = tempCopy()
  const p = join(dir, 'contract', 'transfer-state.json')
  const st = JSON.parse(readFileSync(p, 'utf8'))
  st.deleteWarning.keys.staged = 'delete.warn.nonesuch'
  writeFileSync(p, JSON.stringify(st, null, 2))
  const r = runChecks(dir, { quick: true })
  assert.ok(r.problems.some((m) => m.includes('delete.warn')), r.problems.join('\n'))
})

test('check：现状全绿（quick）', () => {
  const r = runChecks(ROOT, { quick: true })
  assert.deepEqual(r.problems, [])
  assert.equal(r.ok, true)
})

test('check：数据文件改了没跑 gen → sha 不一致要红', () => {
  const dir = tempCopy()
  const p = join(dir, 'contract', 'strings.json')
  const s = JSON.parse(readFileSync(p, 'utf8'))
  s['phase.landed']['zh-Hans'] = '已归档'
  writeFileSync(p, JSON.stringify(s, null, 2))
  const r = runChecks(dir, { quick: true })
  assert.ok(r.problems.some((m) => m.includes('strings.json') && m.includes('sha')), r.problems.join('\n'))
})

test('check：坏夹具要红', () => {
  const dir = tempCopy()
  const p = join(dir, 'contract', 'fixtures', 'tally.json')
  writeFileSync(p, JSON.stringify({ cases: [{ name: 'x', states: ['flying'], expect: { uploading: 0, failed: 0, staged: 0, landed: 0, total: 0 } }] }))
  const r = runChecks(dir, { quick: true })
  assert.ok(r.problems.some((m) => m.includes('fixtures/tally.json')), r.problems.join('\n'))
})

test('check：夹具期望必须与迁移表一致', () => {
  const dir = tempCopy()
  const p = join(dir, 'contract', 'fixtures', 'transitions.json')
  const f = JSON.parse(readFileSync(p, 'utf8'))
  f.cases[0].to = 'arrived'  // waiting + kick 应为 uploading
  writeFileSync(p, JSON.stringify(f))
  const r = runChecks(dir, { quick: true })
  assert.ok(r.problems.some((m) => m.includes('transitions.json') && m.includes('迁移表')), r.problems.join('\n'))
})

test('gen：每个生成物都带 GENERATED 头且落在约定路径', () => {
  const c = loadContract(ROOT)
  const files = outputs(c)
  const expected = [
    'miniprogram/styles/tokens.wxss',
    'miniprogram/utils/contract/states.ts', 'miniprogram/utils/contract/strings.ts', 'miniprogram/utils/contract/capabilities.ts',
    'ios/Sources/Contract/Tokens.swift', 'ios/Sources/Contract/Strings.swift', 'ios/Sources/Contract/States.swift', 'ios/Sources/Contract/Capabilities.swift',
    'android/contract/src/main/kotlin/com/aiworkdeck/contract/Tokens.kt', 'android/contract/src/main/kotlin/com/aiworkdeck/contract/Strings.kt',
    'android/contract/src/main/kotlin/com/aiworkdeck/contract/States.kt', 'android/contract/src/main/kotlin/com/aiworkdeck/contract/Capabilities.kt',
    'harmony/contract/src/main/ets/Tokens.ets', 'harmony/contract/src/main/ets/Strings.ets', 'harmony/contract/src/main/ets/States.ets', 'harmony/contract/src/main/ets/Capabilities.ets', 'harmony/contract/Index.ets',
  ]
  assert.deepEqual([...files.keys()].sort(), expected.sort())
  for (const [p, content] of files) assert.ok(content.includes('GENERATED by contract/tools/gen.mjs'), `${p} 缺生成头`)
})

test('gen：wxss 间距 ×2 出 rpx，字号 px，旧变量名保留', () => {
  const wxss = outputs(loadContract(ROOT)).get('miniprogram/styles/tokens.wxss')!
  assert.match(wxss, /--s4: 32rpx;/)
  assert.match(wxss, /--gutter: 40rpx;/)
  assert.match(wxss, /--t-body: 15px;/)
  assert.match(wxss, /--st-moving: #1E3A8A;/)
  assert.match(wxss, /--dk-rule: rgba\(255, 255, 255, 0\.10\);/)
  assert.match(wxss, /--touch-min: 88rpx;/)
  assert.match(wxss, /\.label \{/)  // footer 工具类保留
})

test('gen：Swift 令牌保留 T.L/T.D/T.S/T.Sp 调用面', () => {
  const swift = outputs(loadContract(ROOT)).get('ios/Sources/Contract/Tokens.swift')!
  assert.match(swift, /enum T \{/)
  assert.match(swift, /static let accent = Color\(hex: 0x1E3A8A\)/)
  assert.match(swift, /static let rule = Color\(\.sRGB, red: 1\.000, green: 1\.000, blue: 1\.000, opacity: 0\.10\)/)
  assert.match(swift, /static let gutter: CGFloat = 20/)
  assert.match(swift, /static let body: CGFloat = 15/)
  assert.match(swift, /static let touchMin: CGFloat = 44/)
})

test('check：生成物被手改要红', () => {
  const dir = tempCopy()
  // 把真实生成物拷进临时根，再改坏一个
  for (const rel of outputs(loadContract(ROOT)).keys()) {
    const src = join(ROOT, rel)
    if (existsSync(src)) cpSync(src, join(dir, rel))
  }
  cpSync(join(ROOT, 'contract', 'tools', 'wxss-footer.css'), join(dir, 'contract', 'tools', 'wxss-footer.css'))
  const p = join(dir, 'miniprogram', 'utils', 'contract', 'strings.ts')
  writeFileSync(p, readFileSync(p, 'utf8').replace('已落盘', '已归档'))
  const r = runChecks(dir, { quick: true })
  assert.ok(r.problems.some((m) => m.includes('miniprogram/utils/contract/strings.ts') && m.includes('过期')), r.problems.join('\n'))
})

test('check：现状全量（含内联扫描）全绿', () => {
  const r = runChecks(ROOT, { quick: false })
  assert.deepEqual(r.problems, [])
})

test('check：内联词典文案要红', () => {
  const dir = tempCopy()
  for (const rel of outputs(loadContract(ROOT)).keys()) {
    const src = join(ROOT, rel)
    if (existsSync(src)) cpSync(src, join(dir, rel))
  }
  cpSync(join(ROOT, 'contract', 'tools', 'wxss-footer.css'), join(dir, 'contract', 'tools', 'wxss-footer.css'))
  const p = join(dir, 'ios', 'Sources', 'Features', 'Foo.swift')
  cpSync(join(ROOT, 'ios', 'Sources', 'Design', 'L10n.swift'), p)  // 任意 swift 文件做载体
  writeFileSync(p, readFileSync(p, 'utf8') + '\nlet x = "已落盘"\n')
  const r = runChecks(dir, { quick: false })
  assert.ok(r.problems.some((m) => m.includes('Foo.swift') && m.includes('内联')), r.problems.join('\n'))
})

test('check：API 副本 sha 与 PINNED 不一致要红', () => {
  const dir = tempCopy()
  for (const rel of outputs(loadContract(ROOT)).keys()) {
    const src = join(ROOT, rel)
    if (existsSync(src)) cpSync(src, join(dir, rel))
  }
  cpSync(join(ROOT, 'contract', 'tools', 'wxss-footer.css'), join(dir, 'contract', 'tools', 'wxss-footer.css'))
  const y = join(dir, 'contract', 'api', 'mobile-v1.yaml')
  writeFileSync(y, readFileSync(y, 'utf8') + '\n# tampered\n')
  const r = runChecks(dir, { quick: true })
  assert.ok(r.problems.some((m) => m.includes('mobile-v1.yaml') && m.includes('PINNED')), r.problems.join('\n'))
})

test('check：带占位的文案被拆开内联也要红', () => {
  const dir = tempCopy()
  for (const rel of outputs(loadContract(ROOT)).keys()) {
    const src = join(ROOT, rel)
    if (existsSync(src)) cpSync(src, join(dir, rel))
  }
  cpSync(join(ROOT, 'contract', 'tools', 'wxss-footer.css'), join(dir, 'contract', 'tools', 'wxss-footer.css'))
  const p = join(dir, 'ios', 'Sources', 'Features', 'Bar.swift')
  cpSync(join(ROOT, 'ios', 'Sources', 'Design', 'L10n.swift'), p)  // 任意 swift 文件做载体
  writeFileSync(p, readFileSync(p, 'utf8') + '\nlet x = Text("含 \\(n) 失败")\n')
  const r = runChecks(dir, { quick: false })
  assert.ok(r.problems.some((m) => m.includes('Bar.swift') && m.includes('失败')), r.problems.join('\n'))
})

test('check：注释里的词典文案不算内联', () => {
  const dir = tempCopy()
  for (const rel of outputs(loadContract(ROOT)).keys()) {
    const src = join(ROOT, rel)
    if (existsSync(src)) cpSync(src, join(dir, rel))
  }
  cpSync(join(ROOT, 'contract', 'tools', 'wxss-footer.css'), join(dir, 'contract', 'tools', 'wxss-footer.css'))
  const p = join(dir, 'ios', 'Sources', 'Features', 'Baz.swift')
  cpSync(join(ROOT, 'ios', 'Sources', 'Design', 'L10n.swift'), p)
  writeFileSync(p, readFileSync(p, 'utf8') + '\n// 这里本该显示 "已落盘"\n/* 删除 3 件 */\n')
  const r = runChecks(dir, { quick: false })
  assert.deepEqual(r.problems.filter((m) => m.includes('Baz.swift')), [])
})

test('check：Android Kotlin 内联文案要红', () => {
  const dir = tempCopy()
  for (const rel of outputs(loadContract(ROOT)).keys()) {
    const src = join(ROOT, rel)
    if (existsSync(src)) cpSync(src, join(dir, rel))
  }
  cpSync(join(ROOT, 'contract', 'tools', 'wxss-footer.css'), join(dir, 'contract', 'tools', 'wxss-footer.css'))
  mkdirSync(join(dir, 'android', 'app', 'src', 'main', 'kotlin'), { recursive: true })
  const p = join(dir, 'android', 'app', 'src', 'main', 'kotlin', 'Foo.kt')
  writeFileSync(p, 'val x = "已落盘"\n')
  const r = runChecks(dir, { quick: false })
  assert.ok(r.problems.some((m) => m.includes('Foo.kt') && m.includes('内联')), r.problems.join('\n'))
})

test('check：capabilities 端名打错要红（改之前 gen 出 "undefined" 而 check 全绿）', () => {
  const dir = tempCopy()
  const p = join(dir, 'contract', 'capabilities.json')
  writeFileSync(p, readFileSync(p, 'utf8').replace('"android": "wxpay-app"', '"andriod": "wxpay-app"'))
  const r = runChecks(dir, { quick: true })
  assert.ok(r.problems.some((m) => m.includes('capabilities.json') && m.includes('android')), r.problems.join('\n'))
})

test('check：capabilities 取值越界要红', () => {
  const dir = tempCopy()
  const p = join(dir, 'contract', 'capabilities.json')
  writeFileSync(p, readFileSync(p, 'utf8').replace('"android": "wxpay-app"', '"android": "wxpay-ap"'))
  const r = runChecks(dir, { quick: true })
  assert.ok(r.problems.some((m) => m.includes('capabilities.json') && m.includes('recharge')), r.problems.join('\n'))
})

test('check：billing 夹具漏一个 kind 要红', () => {
  const dir = tempCopy()
  const p = join(dir, 'contract', 'fixtures', 'billing.json')
  const f = JSON.parse(readFileSync(p, 'utf8'))
  f.envelope = f.envelope.filter((k: { json: { kind?: string } }) => k.json.kind !== 'ALREADY_PAID')
  writeFileSync(p, JSON.stringify(f))
  const r = runChecks(dir, { quick: true })
  assert.ok(r.problems.some((m) => m.includes('billing.json') && m.includes('ALREADY_PAID')), r.problems.join('\n'))
})

test('check：billing 夹具的 expect 与 json 对不上要红', () => {
  const dir = tempCopy()
  const p = join(dir, 'contract', 'fixtures', 'billing.json')
  const f = JSON.parse(readFileSync(p, 'utf8'))
  f.envelope.find((k: { json: { kind?: string } }) => k.json.kind === 'ALREADY_PAID').expect.outTradeNo = null
  writeFileSync(p, JSON.stringify(f))
  const r = runChecks(dir, { quick: true })
  assert.ok(r.problems.some((m) => m.includes('billing.json') && m.includes('outTradeNo')), r.problems.join('\n'))
})

test('金额展示口径：无千分位、两位小数、符号按 currency 取，不跟设备 locale', () => {
  // 参考实现本身也要钉住：123456 分带千分位会是 ¥1,234.56，iOS 的 NumberFormatter(.decimal)
  // 在德语设备上还会给出 ¥1.234,56 —— 两者都与这条口径不符（dev-board#425 二轮复审 N7）
  assert.equal(referenceMoneyDisplay(123456, 'CNY'), '¥1234.56')
  assert.equal(referenceMoneyDisplay(0, 'CNY'), '¥0.00')
  assert.equal(referenceMoneyDisplay(990, 'USD'), '$9.90')
  assert.equal(referenceMoneyDisplay(5, 'CNY'), '¥0.05')
  assert.equal(referenceMoneyDisplay(100, 'EUR'), null, '没约定符号的币种不许猜一个出来')
})

test('check：billing 夹具的 display 与展示口径对不上要红', () => {
  const dir = tempCopy()
  const p = join(dir, 'contract', 'fixtures', 'billing.json')
  const f = JSON.parse(readFileSync(p, 'utf8'))
  // 千分位版本：三端里只有 iOS 的 NumberFormatter 会这么给
  f.balance.find((k: { json: { balanceCents: number } }) => k.json.balanceCents === 123456).display = '¥1,234.56'
  writeFileSync(p, JSON.stringify(f))
  const r = runChecks(dir, { quick: true })
  assert.ok(r.problems.some((m) => m.includes('billing.json') && m.includes('display')), r.problems.join('\n'))
})

test('check：没有任何一端消费的夹具段要留下提示（不报错）', () => {
  const r = runChecks(ROOT, { quick: true })
  assert.deepEqual(r.problems, [])
  for (const section of ['recharge', 'status']) {
    assert.ok(r.notes.some((m) => m.includes('billing.json') && m.includes(section)), r.notes.join('\n'))
  }
  // 已被三端消费的两段不该出现在提示里
  for (const section of ['balance', 'envelope']) {
    assert.ok(!r.notes.some((m) => m.includes(`「${section}」`)), r.notes.join('\n'))
  }
})
