// GENERATED by contract/tools/gen.mjs from contract/*.json — 不要手改，改 contract/ 再跑 gen
export const CLIENT = "miniprogram"
export const CAPS = {
  "backgroundUpload": false,
  "maxVideoSeconds": 60,
  "continuousSegments": true,
  "glassBlur": "runtime",
  "deviceAttestation": false,
  "backgroundRecording": false,
  "recharge": "virtual"
} as const
export const DEGRADED_NOTICE: Record<string, string> = {"backgroundUpload":"cap.noBackgroundUpload","continuousSegments":"cap.segmentedRecording","backgroundRecording":"cap.noBackgroundRecording"}
