// GENERATED by contract/tools/gen.mjs from contract/*.json — 不要手改，改 contract/ 再跑 gen
export interface ContractProduct {
  /** 微信公众平台上的道具 id */
  productId: string
  /** 道具价格，整数分；与公众平台上的价格逐分相等，官网侧另有权威表复核 */
  amountCents: number
}

export interface ContractProducts {
  wxvp: readonly ContractProduct[]
}

export const PRODUCTS: ContractProducts = {
  "wxvp": [
    {
      "productId": "credits_cny_10",
      "amountCents": 1000
    },
    {
      "productId": "credits_cny_50",
      "amountCents": 5000
    },
    {
      "productId": "credits_cny_100",
      "amountCents": 10000
    }
  ]
}
