// GENERATED by contract/tools/gen.mjs from contract/*.json — 不要手改，改 contract/ 再跑 gen
export const CONTRACT_VERSION = 1
export type QueueState = "waiting" | "uploading" | "uploaded" | "arrived" | "failed"
export const STATES: readonly QueueState[] = ["waiting","uploading","uploaded","arrived","failed"]
export const STATE_ALIASES: Record<string, QueueState> = {"moving":"uploading"}
export type Phase = "uploading" | "staged" | "landed"
export const PHASE_OF: Record<QueueState, Phase> = {"waiting":"uploading","uploading":"uploading","failed":"uploading","uploaded":"staged","arrived":"landed"}
export const PHASE_LABEL_KEY: Record<Phase, string> = {"uploading":"phase.uploading","staged":"phase.staged","landed":"phase.landed"}
export const PHASE_DOT: Record<Phase, string> = {"uploading":"S.waiting","staged":"S.moving","landed":"S.arrived"}
export const FAILED_DOT = "S.failed"
export const STATE_TEXT_KEY: Record<QueueState, string> = {"waiting":"state.uploading","uploading":"state.uploading","failed":"state.failed","uploaded":"state.uploaded.detail","arrived":"state.landed"}
export const WHERE_KEY: Record<QueueState, string> = {"waiting":"where.waiting","uploading":"where.uploading","uploaded":"where.uploaded","arrived":"where.arrived","failed":"where.failed"}
export const RETRY_DELAYS_MS: readonly number[] = [5000,15000,45000]
export const MAX_AUTO_RETRIES = 3
export type TransferEvent = "kick" | "http_2xx" | "http_error" | "network_error" | "retry_manual" | "retry_auto" | "status_delivered" | "status_pending" | "app_launch"
export const TRANSITIONS: ReadonlyArray<{ from: QueueState; event: TransferEvent; to: QueueState; guard?: string }> = [
  {
    "from": "waiting",
    "event": "kick",
    "to": "uploading"
  },
  {
    "from": "uploading",
    "event": "http_2xx",
    "to": "uploaded"
  },
  {
    "from": "uploading",
    "event": "http_error",
    "to": "failed"
  },
  {
    "from": "uploading",
    "event": "network_error",
    "to": "failed"
  },
  {
    "from": "failed",
    "event": "retry_manual",
    "to": "waiting"
  },
  {
    "from": "failed",
    "event": "retry_auto",
    "to": "waiting",
    "guard": "attempts <= maxAutoRetries"
  },
  {
    "from": "uploaded",
    "event": "status_delivered",
    "to": "arrived"
  },
  {
    "from": "uploaded",
    "event": "status_pending",
    "to": "uploaded"
  },
  {
    "from": "uploading",
    "event": "app_launch",
    "to": "waiting"
  },
  {
    "from": "failed",
    "event": "app_launch",
    "to": "waiting",
    "guard": "attempts <= maxAutoRetries"
  }
]
export const DELETE_WARN_ORDER: readonly Phase[] = ["uploading","staged","landed"]
export const DELETE_WARN_LEVEL: Record<Phase, 'unsent' | 'staged' | 'landed'> = {"uploading":"unsent","staged":"staged","landed":"landed"}
export const DELETE_WARN_KEY: Record<'unsent' | 'staged' | 'landed', string> = {"unsent":"delete.warn.unsent","staged":"delete.warn.staged","landed":"delete.warn.landed"}
