// GENERATED by contract/tools/gen.mjs from contract/*.json — 不要手改，改 contract/ 再跑 gen
export const STRINGS: Record<string, { 'zh-Hans': string; en: string }> = {
  "phase.uploading": {
    "zh-Hans": "上传中",
    "en": "Uploading"
  },
  "phase.staged": {
    "zh-Hans": "已暂存",
    "en": "Staged"
  },
  "phase.landed": {
    "zh-Hans": "已落盘",
    "en": "Landed"
  },
  "state.uploading": {
    "zh-Hans": "上传中",
    "en": "Uploading"
  },
  "state.failed": {
    "zh-Hans": "上传失败",
    "en": "Upload failed"
  },
  "state.uploaded": {
    "zh-Hans": "已暂存",
    "en": "Staged"
  },
  "state.uploaded.detail": {
    "zh-Hans": "已暂存 · 等待桌面端接收",
    "en": "Staged · waiting for desktop"
  },
  "state.landed": {
    "zh-Hans": "已落盘",
    "en": "Landed"
  },
  "where.waiting": {
    "zh-Hans": "在手机上",
    "en": "On this phone"
  },
  "where.uploading": {
    "zh-Hans": "在路上",
    "en": "In transit"
  },
  "where.uploaded": {
    "zh-Hans": "在中转区，等电脑取回",
    "en": "In relay, waiting for your computer"
  },
  "where.arrived": {
    "zh-Hans": "在你电脑上",
    "en": "On your computer"
  },
  "where.failed": {
    "zh-Hans": "需重试",
    "en": "Needs retry"
  },
  "tally.failedSuffix": {
    "zh-Hans": "含 {m} 失败",
    "en": "{m} failed"
  },
  "tally.summary": {
    "zh-Hans": "上传中 {u} 张{f}，已暂存 {s} 张，已落盘 {l} 张",
    "en": "{u} uploading{f}, {s} staged, {l} landed"
  },
  "tally.summary.failedPart": {
    "zh-Hans": "（含 {m} 失败）",
    "en": " ({m} failed)"
  },
  "queue.section.uploading": {
    "zh-Hans": "上传中",
    "en": "Uploading"
  },
  "queue.section.failed": {
    "zh-Hans": "失败 · 需要处理",
    "en": "Failed · needs attention"
  },
  "queue.section.staged": {
    "zh-Hans": "已暂存 · 等电脑取回",
    "en": "Staged · waiting for your computer"
  },
  "queue.section.landed": {
    "zh-Hans": "已落盘",
    "en": "Landed"
  },
  "delete.title": {
    "zh-Hans": "删除 {n} 件",
    "en": "Delete {n} items"
  },
  "delete.warn.unsent": {
    "zh-Hans": "其中 {n} 件还没送出去。删了就没了，无法找回。",
    "en": "{n} of these have not been sent. Deleting them is permanent."
  },
  "delete.warn.staged": {
    "zh-Hans": "其中 {n} 件电脑还没取回。中转区 7 天后清理，电脑若未及时接收，这些影像将无法找回。",
    "en": "{n} of these have not reached your computer. The relay clears after 7 days; if the desktop does not collect them in time they cannot be recovered."
  },
  "delete.warn.landed": {
    "zh-Hans": "删除 {n} 件本地原图？电脑上已有副本。",
    "en": "Delete {n} local originals? Your computer already has copies."
  },
  "cap.noBackgroundUpload": {
    "zh-Hans": "本端不支持后台上传，请保持页面打开直到上传完成",
    "en": "This client cannot upload in the background. Keep the page open until uploads finish."
  },
  "cap.segmentedRecording": {
    "zh-Hans": "本端录像为记录用途，证据用途请用 iOS 端",
    "en": "Video on this client is for record-keeping. Use the iOS app for evidentiary recording."
  },
  "empty.projects": {
    "zh-Hans": "桌面端用同一手机号登录并保持运行，项目约一分钟内出现在这里",
    "en": "Sign in to the desktop app with the same phone number and keep it running. Projects appear here within about a minute."
  },
  "error.uploadFailed": {
    "zh-Hans": "上传失败（{code}）",
    "en": "Upload failed ({code})"
  }
}
