// GENERATED by contract/tools/gen.mjs from contract/*.json — 不要手改，改 contract/ 再跑 gen
enum ContractCapabilities {
    static let client = "ios"
    static let backgroundUpload: Bool = true
    static let maxVideoSeconds: Int? = nil
    static let continuousSegments: Bool = false
    /// true / false，或 "runtime" 表示运行时探测
    static let glassBlur: String = "true"
    static let deviceAttestation: Bool = true
    static let degradedNotice: [String: String] = ["backgroundUpload": "cap.noBackgroundUpload", "continuousSegments": "cap.segmentedRecording"]
}
