// GENERATED by contract/tools/gen.mjs from contract/*.json — 不要手改，改 contract/ 再跑 gen
enum ContractCapabilities {
    static let client = "ios"
    static let backgroundUpload: Bool = true
    static let maxVideoSeconds: Int? = nil
    static let continuousSegments: Bool = false
    /// true / false，或 "runtime" 表示运行时探测
    static let glassBlur: String = "true"
    static let deviceAttestation: Bool = true
    /// 充值通道："iap" / "virtual" / "wxpay-app" / "external"（只放引导入口），或 "false" 表示本端连入口都不放
    static let recharge: String = "iap"
    /// 能否登录国际站（workdeck.ai）账号
    static let intlAccount: Bool = true
    static let degradedNotice: [String: String] = ["backgroundUpload": "cap.noBackgroundUpload", "continuousSegments": "cap.segmentedRecording", "backgroundRecording": "cap.noBackgroundRecording", "intlAccount": "cap.noIntlAccount"]
}
