// GENERATED by contract/tools/gen.mjs from contract/*.json — 不要手改，改 contract/ 再跑 gen
/// App Store Connect 上的消耗型商品。
struct ContractProduct: Equatable, Sendable {
    /// App Store Connect 上的商品 id
    let productId: String
    /// 站点币种面值，整数分；展示价格用 StoreKit 的 displayPrice，不要拿它自己格式化
    let amountCents: Int
}

enum ContractProducts {
    static let appstore: [ContractProduct] = [
        ContractProduct(productId: "credits.cny.50", amountCents: 5000),
        ContractProduct(productId: "credits.cny.100", amountCents: 10000),
        ContractProduct(productId: "credits.cny.300", amountCents: 30000),
    ]
}
