// GENERATED by contract/tools/gen.mjs from contract/*.json — 不要手改，改 contract/ 再跑 gen
enum ContractStates {
    static let version = 1
    static let states: [String] = ["waiting","uploading","uploaded","arrived","failed"]
    static let aliases: [String: String] = ["moving": "uploading"]
    static let phaseOf: [String: String] = ["waiting": "uploading", "uploading": "uploading", "failed": "uploading", "uploaded": "staged", "arrived": "landed"]
    static let phaseLabelKey: [String: String] = ["uploading": "phase.uploading", "staged": "phase.staged", "landed": "phase.landed"]
    static let phaseDot: [String: String] = ["uploading": "S.waiting", "staged": "S.moving", "landed": "S.arrived"]
    static let failedDot = "S.failed"
    static let stateTextKey: [String: String] = ["waiting": "state.uploading", "uploading": "state.uploading", "failed": "state.failed", "uploaded": "state.uploaded.detail", "arrived": "state.landed"]
    static let whereKey: [String: String] = ["waiting": "where.waiting", "uploading": "where.uploading", "uploaded": "where.uploaded", "arrived": "where.arrived", "failed": "where.failed"]
    static let retryDelaysMs: [Int] = [5000,15000,45000]
    static let maxAutoRetries = 3
    static let events: [String] = ["kick","http_2xx","http_error","network_error","retry_manual","retry_auto","status_delivered","status_pending","app_launch"]
    static let transitions: [(from: String, event: String, to: String, guard: String?)] = [
        (from: "waiting", event: "kick", to: "uploading", guard: nil),
        (from: "uploading", event: "http_2xx", to: "uploaded", guard: nil),
        (from: "uploading", event: "http_error", to: "failed", guard: nil),
        (from: "uploading", event: "network_error", to: "failed", guard: nil),
        (from: "failed", event: "retry_manual", to: "waiting", guard: nil),
        (from: "failed", event: "retry_auto", to: "waiting", guard: "attempts <= maxAutoRetries"),
        (from: "uploaded", event: "status_delivered", to: "arrived", guard: nil),
        (from: "uploaded", event: "status_pending", to: "uploaded", guard: nil),
        (from: "uploading", event: "app_launch", to: "waiting", guard: nil),
        (from: "failed", event: "app_launch", to: "waiting", guard: "attempts <= maxAutoRetries"),
    ]
    static let deleteWarnOrder: [String] = ["uploading","staged","landed"]
    static let deleteWarnLevel: [String: String] = ["uploading": "unsent", "staged": "staged", "landed": "landed"]
    static let deleteWarnKey: [String: String] = ["unsent": "delete.warn.unsent", "staged": "delete.warn.staged", "landed": "delete.warn.landed"]
}
