// GENERATED by contract/tools/gen.mjs from contract/*.json — 不要手改，改 contract/ 再跑 gen
import SwiftUI

/// 设计令牌。F（字体）与 A（动效）在 Design/Typography.swift 里以 extension 补齐。
enum T {
    enum L {
        static let bg = Color(hex: 0xFCFBF7)
        static let sunken = Color(hex: 0xF1EFE7)
        static let fg = Color(hex: 0x2B2A26)
        static let fgMuted = Color(hex: 0x6B675C)
        static let fgFaint = Color(hex: 0xA8A296)
        static let rule = Color(hex: 0xEAE7DD)
        static let ruleStrong = Color(hex: 0xDDD8CA)
        static let accent = Color(hex: 0x2E5A50)
        static let accentWash = Color(hex: 0xE3EDE9)
    }

    enum D {
        static let bg = Color(hex: 0x191713)
        static let surface = Color(hex: 0x221F1A)
        static let fg = Color(hex: 0xEDE9DF)
        static let fgMuted = Color(hex: 0xB0AA9C)
        static let rule = Color(.sRGB, red: 1.000, green: 1.000, blue: 1.000, opacity: 0.10)
    }

    enum S {
        static let waiting = Color(hex: 0x8A6320)
        static let moving = Color(hex: 0x3C5A73)
        static let arrived = Color(hex: 0x2E5A50)
        static let failed = Color(hex: 0xB5483C)
        static let waitingOnDark = Color(hex: 0xD19C3D)
        static let movingOnDark = Color(hex: 0x93B3C6)
        static let arrivedOnDark = Color(hex: 0x89A8A0)
    }

    enum Sp {
        static let s1: CGFloat = 4
        static let s2: CGFloat = 8
        static let s3: CGFloat = 12
        static let s4: CGFloat = 16
        static let s5: CGFloat = 20
        static let s6: CGFloat = 24
        static let s8: CGFloat = 32
        static let s10: CGFloat = 40
        static let s16: CGFloat = 64
        static let gutter: CGFloat = 20
    }

    enum Ty {
        static let hero: CGFloat = 44
        static let display: CGFloat = 30
        static let title: CGFloat = 21
        static let heading: CGFloat = 16
        static let body: CGFloat = 15
        static let small: CGFloat = 13
        static let micro: CGFloat = 11
        static let nano: CGFloat = 10
    }

    enum Motion {
        static let fast: Double = 0.14
        static let base: Double = 0.22
        static let slow: Double = 0.32
    }
    static let touchMin: CGFloat = 44
    static let contractVersion = 1
}
