// GENERATED by contract/tools/gen.mjs from contract/*.json — 不要手改，改 contract/ 再跑 gen
package com.aiworkdeck.contract

object ContractCapabilities {
    const val client: String = "android"
    const val backgroundUpload: Boolean = true
    val maxVideoSeconds: Int? = null
    const val continuousSegments: Boolean = false
    /** "true" / "false" / "runtime" */
    const val glassBlur: String = "runtime"
    const val deviceAttestation: Boolean = false
    val degradedNotice: Map<String, String> = mapOf("backgroundUpload" to "cap.noBackgroundUpload", "continuousSegments" to "cap.segmentedRecording")
}
