// GENERATED by contract/tools/gen.mjs from contract/*.json — 不要手改，改 contract/ 再跑 gen
package com.aiworkdeck.contract

data class Transition(val from: String, val event: String, val to: String, val guard: String?)

object ContractStates {
    const val version: Int = 1
    val states: List<String> = listOf("waiting", "uploading", "uploaded", "arrived", "failed")
    val aliases: Map<String, String> = mapOf("moving" to "uploading")
    val phaseOf: Map<String, String> = mapOf("waiting" to "uploading", "uploading" to "uploading", "failed" to "uploading", "uploaded" to "staged", "arrived" to "landed")
    val phaseLabelKey: Map<String, String> = mapOf("uploading" to "phase.uploading", "staged" to "phase.staged", "landed" to "phase.landed")
    val phaseDot: Map<String, String> = mapOf("uploading" to "S.waiting", "staged" to "S.moving", "landed" to "S.arrived")
    const val failedDot: String = "S.failed"
    val stateTextKey: Map<String, String> = mapOf("waiting" to "state.uploading", "uploading" to "state.uploading", "failed" to "state.failed", "uploaded" to "state.uploaded.detail", "arrived" to "state.landed")
    val whereKey: Map<String, String> = mapOf("waiting" to "where.waiting", "uploading" to "where.uploading", "uploaded" to "where.uploaded", "arrived" to "where.arrived", "failed" to "where.failed")
    val retryDelaysMs: List<Int> = listOf(5000, 15000, 45000)
    const val maxAutoRetries: Int = 3
    val events: List<String> = listOf("kick", "http_2xx", "http_error", "network_error", "retry_manual", "retry_auto", "status_delivered", "status_pending", "app_launch")
    val transitions: List<Transition> = listOf(
        Transition("waiting", "kick", "uploading", null),
        Transition("uploading", "http_2xx", "uploaded", null),
        Transition("uploading", "http_error", "failed", null),
        Transition("uploading", "network_error", "failed", null),
        Transition("failed", "retry_manual", "waiting", null),
        Transition("failed", "retry_auto", "waiting", "attempts <= maxAutoRetries"),
        Transition("uploaded", "status_delivered", "arrived", null),
        Transition("uploaded", "status_pending", "uploaded", null),
        Transition("uploading", "app_launch", "waiting", null),
        Transition("failed", "app_launch", "waiting", "attempts <= maxAutoRetries"),
    )
    val deleteWarnOrder: List<String> = listOf("uploading", "staged", "landed")
    val deleteWarnLevel: Map<String, String> = mapOf("uploading" to "unsent", "staged" to "staged", "landed" to "landed")
    val deleteWarnKey: Map<String, String> = mapOf("unsent" to "delete.warn.unsent", "staged" to "delete.warn.staged", "landed" to "delete.warn.landed")
}
