// GENERATED by contract/tools/gen.mjs from contract/*.json — 不要手改，改 contract/ 再跑 gen
package com.aiworkdeck.contract

object ContractStrings {
    val table: Map<String, Map<String, String>> = mapOf(
        "phase.uploading" to mapOf("zh-Hans" to "上传中", "en" to "Uploading"),
        "phase.staged" to mapOf("zh-Hans" to "已暂存", "en" to "Staged"),
        "phase.landed" to mapOf("zh-Hans" to "已落盘", "en" to "Landed"),
        "state.uploading" to mapOf("zh-Hans" to "上传中", "en" to "Uploading"),
        "state.failed" to mapOf("zh-Hans" to "上传失败", "en" to "Upload failed"),
        "state.uploaded" to mapOf("zh-Hans" to "已暂存", "en" to "Staged"),
        "state.uploaded.detail" to mapOf("zh-Hans" to "已暂存 · 等待桌面端接收", "en" to "Staged · waiting for desktop"),
        "state.landed" to mapOf("zh-Hans" to "已落盘", "en" to "Landed"),
        "where.waiting" to mapOf("zh-Hans" to "在手机上", "en" to "On this phone"),
        "where.uploading" to mapOf("zh-Hans" to "在路上", "en" to "In transit"),
        "where.uploaded" to mapOf("zh-Hans" to "在中转区，等电脑取回", "en" to "In relay, waiting for your computer"),
        "where.arrived" to mapOf("zh-Hans" to "在你电脑上", "en" to "On your computer"),
        "where.failed" to mapOf("zh-Hans" to "需重试", "en" to "Needs retry"),
        "tally.failedSuffix" to mapOf("zh-Hans" to "含 {m} 失败", "en" to "{m} failed"),
        "tally.summary" to mapOf("zh-Hans" to "上传中 {u} 张{f}，已暂存 {s} 张，已落盘 {l} 张", "en" to "{u} uploading{f}, {s} staged, {l} landed"),
        "tally.summary.failedPart" to mapOf("zh-Hans" to "（含 {m} 失败）", "en" to " ({m} failed)"),
        "queue.section.uploading" to mapOf("zh-Hans" to "上传中", "en" to "Uploading"),
        "queue.section.failed" to mapOf("zh-Hans" to "失败 · 需要处理", "en" to "Failed · needs attention"),
        "queue.section.staged" to mapOf("zh-Hans" to "已暂存 · 等电脑取回", "en" to "Staged · waiting for your computer"),
        "queue.section.landed" to mapOf("zh-Hans" to "已落盘", "en" to "Landed"),
        "delete.title" to mapOf("zh-Hans" to "删除 {n} 件", "en" to "Delete {n} items"),
        "delete.warn.unsent" to mapOf("zh-Hans" to "其中 {n} 件还没送出去。删了就没了，无法找回。", "en" to "{n} of these have not been sent. Deleting them is permanent."),
        "delete.warn.staged" to mapOf("zh-Hans" to "其中 {n} 件电脑还没取回。中转区 7 天后清理，电脑若未及时接收，这些影像将无法找回。", "en" to "{n} of these have not reached your computer. The relay clears after 7 days; if the desktop does not collect them in time they cannot be recovered."),
        "delete.warn.landed" to mapOf("zh-Hans" to "删除 {n} 件本地原图？电脑上已有副本。", "en" to "Delete {n} local originals? Your computer already has copies."),
        "cap.noBackgroundUpload" to mapOf("zh-Hans" to "本端不支持后台上传，请保持页面打开直到上传完成", "en" to "This client cannot upload in the background. Keep the page open until uploads finish."),
        "cap.segmentedRecording" to mapOf("zh-Hans" to "本端录像为记录用途，证据用途请用 iOS 端", "en" to "Video on this client is for record-keeping. Use the iOS app for evidentiary recording."),
        "empty.projects" to mapOf("zh-Hans" to "桌面端用同一手机号登录并保持运行，项目约一分钟内出现在这里", "en" to "Sign in to the desktop app with the same phone number and keep it running. Projects appear here within about a minute."),
        "error.uploadFailed" to mapOf("zh-Hans" to "上传失败（{code}）", "en" to "Upload failed ({code})"),
    )
}
