// GENERATED by contract/tools/gen.mjs from contract/*.json — 不要手改，改 contract/ 再跑 gen
package com.aiworkdeck.contract

/** 颜色为 ARGB Long；间距单位 dp，字号单位 sp。 */
object T {
    object L {
        const val bg: Long = 0xFFFFFFFFL
        const val sunken: Long = 0xFFFAFAFAL
        const val fg: Long = 0xFF0A0E1AL
        const val fgMuted: Long = 0xFF6B7280L
        const val fgFaint: Long = 0xFF9CA3AFL
        const val rule: Long = 0xFFECEEF1L
        const val ruleStrong: Long = 0xFFD4D8DEL
        const val accent: Long = 0xFF1E3A8AL
        const val accentWash: Long = 0xFFF4F6FBL
    }
    object D {
        const val bg: Long = 0xFF0A0B0DL
        const val surface: Long = 0xFF141619L
        const val fg: Long = 0xFFF5F6F7L
        const val fgMuted: Long = 0xFF8A8F98L
        const val rule: Long = 0x1AFFFFFFL
    }
    object S {
        const val waiting: Long = 0xFFC2410CL
        const val moving: Long = 0xFF1E3A8AL
        const val arrived: Long = 0xFF15803DL
        const val failed: Long = 0xFFB91C1CL
        const val waitingOnDark: Long = 0xFFF97316L
        const val movingOnDark: Long = 0xFF60A5FAL
        const val arrivedOnDark: Long = 0xFF4ADE80L
    }
    object Sp {
        const val s1: Int = 4
        const val s2: Int = 8
        const val s3: Int = 12
        const val s4: Int = 16
        const val s5: Int = 20
        const val s6: Int = 24
        const val s8: Int = 32
        const val s10: Int = 40
        const val s16: Int = 64
        const val gutter: Int = 20
    }
    object Ty {
        const val hero: Int = 44
        const val display: Int = 30
        const val title: Int = 21
        const val heading: Int = 16
        const val body: Int = 15
        const val small: Int = 13
        const val micro: Int = 11
        const val nano: Int = 10
    }
    object Motion { const val fastMs: Int = 140; const val baseMs: Int = 220; const val slowMs: Int = 320 }
    const val touchMin: Int = 44
    const val contractVersion: Int = 1
}
