// GENERATED by contract/tools/gen.mjs from contract/*.json — 不要手改，改 contract/ 再跑 gen
package com.aiworkdeck.contract

/** 颜色为 ARGB Long；间距单位 dp，字号单位 sp。 */
object T {
    object L {
        const val bg: Long = 0xFFFCFBF7L
        const val sunken: Long = 0xFFF1EFE7L
        const val fg: Long = 0xFF2B2A26L
        const val fgMuted: Long = 0xFF6B675CL
        const val fgFaint: Long = 0xFFA8A296L
        const val rule: Long = 0xFFEAE7DDL
        const val ruleStrong: Long = 0xFFDDD8CAL
        const val accent: Long = 0xFF2E5A50L
        const val accentWash: Long = 0xFFE3EDE9L
    }
    object D {
        const val bg: Long = 0xFF191713L
        const val surface: Long = 0xFF221F1AL
        const val fg: Long = 0xFFEDE9DFL
        const val fgMuted: Long = 0xFFB0AA9CL
        const val rule: Long = 0x1AFFFFFFL
    }
    object S {
        const val waiting: Long = 0xFF8A6320L
        const val moving: Long = 0xFF3C5A73L
        const val arrived: Long = 0xFF2E5A50L
        const val failed: Long = 0xFFB5483CL
        const val waitingOnDark: Long = 0xFFD19C3DL
        const val movingOnDark: Long = 0xFF93B3C6L
        const val arrivedOnDark: Long = 0xFF89A8A0L
    }
    object Sp {
        const val s1: Int = 4
        const val s2: Int = 8
        const val s3: Int = 12
        const val s4: Int = 16
        const val s5: Int = 20
        const val s6: Int = 24
        const val s8: Int = 32
        const val s10: Int = 40
        const val s16: Int = 64
        const val gutter: Int = 20
    }
    object Ty {
        const val hero: Int = 44
        const val display: Int = 30
        const val title: Int = 21
        const val heading: Int = 16
        const val body: Int = 15
        const val small: Int = 13
        const val micro: Int = 11
        const val nano: Int = 10
    }
    object Motion { const val fastMs: Int = 140; const val baseMs: Int = 220; const val slowMs: Int = 320 }
    const val touchMin: Int = 44
    const val contractVersion: Int = 1
}
